### ISSUE TITLE
Unable to update submodules

### ISSUE THREAD

**Issue by sjovanovic** [wheaney/XRLinuxDriver#42]
I am unable to update submodules because I don't have access to GitLab so I get permission denied.
How to update submodules without having to create a GitLab account?

**Comment by xM8WVqaG** [comment]
Replace `git@gitlab.com:` with `https://gitlab.com/` in [`.gitmodules`](https://github.com/wheaney/XRLinuxDriver/blob/main/.gitmodules#L3).
```diff
-	url = git@gitlab.com:TheJackiMonster/nrealAirLinuxDriver.git
+	url = https://gitlab.com/TheJackiMonster/nrealAirLinuxDriver.git
```
The GitLab repo is public, so you don't need to authenticate via SSH to pull it.

**Comment by sjovanovic** [comment]
Thanks. After this `git submodule update` command works.

**Comment by wheaney** [comment]
This is fixed now.
