### ISSUE TITLE
UA_API_SECRET missing error

### ISSUE THREAD

**Issue by sjovanovic** [wheaney/XRLinuxDriver#43]
when running `bin/package` I get the error that the UA_API_SECRET environment variable is missing. This seems to be related to google analytics.

Can I build without using Google Analytics?

**Comment by wheaney** [comment]
Yeah I'm surprised I made it required for the build because the metrics plugin handles it not being set: https://github.com/wheaney/XRLinuxDriver/blob/82d38ce285e68df8671d7516480391b589a7f78f/src/plugins/metrics.c#L65

So you should be able to just remove that check from the build.

**Comment by wheaney** [comment]
This should be resolved now.
