### ISSUE TITLE
display frames via usb-c

### ISSUE THREAD

**Issue by mahdizynali** [wheaney/XRLinuxDriver#55]
hi.
i was wonder if it's possible to transfer and display frames or images via usb-c to usb-c from pc to glasses like android phones.
this driver recognizes glasses and have some output acts, but how can i send frames into glass and display them ?

**Comment by wheaney** [comment]
When you plug your glasses in to any device (phone, PC, steam deck, etc...), that device just treats it like a monitor. So if you have a USB-C port on your device that *ALSO* supports DisplayPort-alt mode, or you have an adapter that allows you to plug your glasses into a standard HDMI or DisplayPort port, then it will be able to show content on your glasses as if you had plugged in any kind of monitor. This driver repo isn't actually responsible for any of that. Whether or not is works is purely a question of whether your hardware supports it or you have the proper adapter.
