### ISSUE TITLE
Strange SBS mode - Viture One

### ISSUE THREAD

**Issue by hodasemi** [wheaney/XRLinuxDriver#64]
The newest version of breezy-gnome exposes the sbs-mode. If I enable it, it gets triggered, as it should I guess. The problem is that the screens are splitted on both eyes. That means the left eye sees the left part of the screen and the right eye the right part, but the combined image makes no sense (causes even a bit of headache).

**Comment by wheaney** [comment]
@hodasemi does this still happen for you?

**Comment by hodasemi** [comment]
It is fixed for me. thanks :)
