### ISSUE TITLE
AUR: wayland-client not found

### ISSUE THREAD

**Issue by mario-aleo** [wheaney/XRLinuxDriver#77]
I`ve been trying to install the **xr-driver-git** using yay, but it's yielding an error?

```
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - wayland-client

Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:841 (_pkg_check_modules_internal)
  CMakeLists.txt:41 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
==> ERROR: A failure occurred in build().

```

I have **xorg-xwayland** installed and can't find a package explicit named **wayland-client**.
What am I missing here?

**Comment by wheaney** [comment]
Can you try this? `sudo pacman -S wayland`
After that, you may also need `sudo pacman -S wayland-protocols`

Let me know if that resolves it.

**Comment by mario-aleo** [comment]
It did worked, that was totally my fault.
But now I'm getting an: missing libudev, I'm trying to install it but without success though I have just started trying.

**Comment by wheaney** [comment]
Try `sudo pacman -S systemd-libs and libusb0`

**Comment by wheaney** [comment]
So I was just looking at my PKGBUILD and my `depends` list appears to be complete: it will pull in `hidapi` and `libusb` which pull in the `systemd-libs`. Are you doing `makepkg` directly? Or using a tool like `yay`?

**Comment by wheaney** [comment]
Just pushed an update to my PKGBUILD to add the wayland dependency. I'd recommend using a tool like `yay` so it does all the dependency management for you.

**Comment by mario-aleo** [comment]
To be honest, I'm currently only using yay, I'm not sure why it is downloading some dependencies and missing others :(

**Comment by wheaney** [comment]
Can you see if installing `systemd-libs` yourself solves it?

**Comment by mario-aleo** [comment]
Sorry for the late reply.
It's working fine now, thanks :)

**Comment by mario-aleo** [comment]
Closing

**Comment by wheaney** [comment]
Great to hear it's working now. Let me know which dependencies fixed it.

**Comment by mario-aleo** [comment]
systemd-libs

**Comment by wheaney** [comment]
I've added that to the dependencies, thanks!
